title: A Jekyll Blog Test
author:
  name: David M. Hollenstein
  email: david.hollenstein@maxperutzlabs.ac.at

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  A repository to test jekyll for creating a blog on github pages. The
  page should list all blog posts and provide a way to navigate to the
  individual posts. The page should also provide a way to comment on the
  posts. The blog posts should look nice on mobile devices.

baseurl: "/jekyll-blog-test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: hollenstein/minima
plugins:
  - jekyll-feed

# Theme-specific settings
header_pages:
  - blog.html
  - about.md

minima:
  show_excerpts: true
  social_links:
    - title: hollenstein at GitHub
      icon_name: github
      icon_class: brands
      url: "https://github.com/hollenstein"
    - title: hollenstein at Bluesky
      icon_name: square-bluesky
      icon_class: brands
      url: "https://bsky.app/profile/hollenstein.bsky.social"
    - title: Max Perutz Labs Mass Spectrometry Facility
      icon_name: globe
      icon_class: solid
      url: "https://www.maxperutzlabs.ac.at/research/facilities/mass-spectrometry-facility"

# Custom settings
num_latest_posts: 3  # Number of latest posts to show on the home page